apiVersion: apps/v1
kind: Deployment
metadata:
  name: __DEPLOY_NAME__
  namespace: __NAMESPACE__
  labels:
    app: __APP_LABEL__
spec:
  selector:
    matchLabels:
      app: __APP_LABEL__
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: __APP_LABEL__
    spec:
      containers:
        - image: docker.elastic.co/kibana/kibana:6.6.0
          name: kibana
          env:
            - name: ELASTICSEARCH_URL
              value: http://10.244.4.153:9203
