apiVersion: apps/v1
kind: Deployment
metadata:
  name: kchain-kibana
  namespace: kbcs
  labels:
    app: kchain-kibana
spec:
  selector:
    matchLabels:
      app: kchain-kibana
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: kchain-kibana
    spec:
      containers:
        - image: docker.elastic.co/kibana/kibana:6.6.0
          name: kibana
          env:
            - name: ELASTICSEARCH_URL
              value: http://10.244.4.153:9203
            - name: SERVER_BASEPATH
              value: catkibana
