apiVersion: v1
kind: Service
metadata:
  name: kchain-kibana
  namespace: kbcs
  labels:
    app: kchain-kibana

spec:
  type: NodePort
  ports:
    - name: normal
      protocol: TCP
      port: 5601
      targetPort: 5601


  selector:
    app: kchain-kibana
