apiVersion: v1
kind: Service
metadata:
  name: kchain-redis
  namespace: kbcs
  labels:
    app: kchain-redis

spec:
  type: NodePort
  ports:
    - name: normal
      protocol: TCP
      port: 6379
      targetPort: 6379


  selector:
    app: kchain-redis
